# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 18:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=80)),
                ('year', models.CharField(max_length=7)),
                ('semester', models.CharField(max_length=7)),
                ('unit', models.CharField(max_length=80)),
                ('size', models.CharField(max_length=80)),
                ('file_type', models.CharField(max_length=80)),
                ('upload', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='MyDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=80)),
                ('book', models.ManyToManyField(to='somo.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=80)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('unit', models.CharField(max_length=80)),
                ('course', models.ManyToManyField(to='somo.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.IntegerField(default=0)),
                ('mobile', models.CharField(max_length=13)),
                ('reg', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to=b'')),
                ('status', models.IntegerField(default=0)),
                ('course_id', models.ManyToManyField(to='somo.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='course',
            field=models.ManyToManyField(to='somo.Course'),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
