# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somo', '0002_auto_20170511_0231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='upload',
            new_name='document',
        ),
    ]
