# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somo', '0004_myupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='course',
        ),
    ]
